import 'dotenv/config';
import {
  Client, GatewayIntentBits, Partials,
  ActionRowBuilder, StringSelectMenuBuilder,
  ButtonBuilder, ButtonStyle,
  ContainerBuilder, MediaGalleryItemBuilder,
  SeparatorSpacingSize,
  MessageFlags
} from 'discord.js';
import { REST as DiscordREST } from '@discordjs/rest';
import { Routes } from 'discord.js';

console.log('[boot] generated by exporter with keepalive');

const client = new Client({
  intents: [GatewayIntentBits.Guilds, GatewayIntentBits.GuildMessages, GatewayIntentBits.MessageContent],
  partials: [Partials.Channel]
});

client.once('ready', () => console.log('[ready]', client.user.tag));

async function ensureCommands(){
  const token = process.env.DISCORD_TOKEN, appId = process.env.APPLICATION_ID, guildId = process.env.GUILD_ID;
  if (!token || !appId || !guildId) return;
  const rest = new DiscordREST({ version:'10' }).setToken(token);
  const body = [{ name:'rustify', description:'Открыть проект Rustify (CV2)', options:[] }];
  try { await rest.put(Routes.applicationGuildCommands(appId, guildId), { body }); console.log('[commands] registered', guildId); }
  catch(e){ console.warn('[commands] register failed', (e && e.rawError) ? e.rawError : e); }
}

client.on('interactionCreate', async (interaction) => {
  try {
    if (interaction.isChatInputCommand() && interaction.commandName === 'rustify') {
      await interaction.deferReply({ ephemeral: false });
      const mainContainer = new ContainerBuilder()

await interaction.editReply({
  flags: MessageFlags.IsComponentsV2,
  components: [mainContainer]
});
      return;
    }
  } catch (err) {
    console.error('[interaction] error', err);
    try { await interaction.reply({ content: 'Ошибка обработки', ephemeral: true }); } catch {}
  }
});

await ensureCommands();
await client.login(process.env.DISCORD_TOKEN);

// --- keepalive for Render Web Service ---
import http from 'node:http';
const port = process.env.PORT || 3000;
http.createServer((_, res) => {
  res.writeHead(200, { 'Content-Type': 'text/plain' });
  res.end('Bot is running
');
}).listen(port, () => console.log('[http] keepalive on', port));